version: '3.4'

services:

  rabbitmq:
   container_name: rabbitmq
   ports:
    - "15672:15672"

  catalog-data:
   container_name: catalog-data
   environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=${SA_PASSWORD}
   ports:
    - "1433:1433"
   volumes:
    - microshop-catalog-data:/var/opt/mssql

  catalog-api:
    image: catalog-api:dev
    container_name: catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      args:
       BUILD_MODE: Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=catalog-data;Database=catalog_db;User Id=sa;Password=${SA_PASSWORD};Persist Security Info=true;
      - RabbitMQSettings__HostName=rabbitmq
      - RabbitMQSettings__ClientName=Catalog,
      - RabbitMQSettings__UserName=${RABBITMQ_USER}
      - RabbitMQSettings__Password=${RABBITMQ_PASSWORD}
      - RabbitMQSettings__Retries=3
    ports:
      - "5000:80"

  basket-api:
   image: basket-api:dev
   container_name: basket-api
   build:
    context: .
    dockerfile: Services/Basket/Basket.API/Dockerfile
    args:
     BUILD_MODE: Debug
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:80
     - ConnectionStrings__DefaultConnection=;
     - RabbitMQSettings__HostName=rabbitmq
     - RabbitMQSettings__ClientName=Basket,
     - RabbitMQSettings__UserName=${RABBITMQ_USER}
     - RabbitMQSettings__Password=${RABBITMQ_PASSWORD}
     - RabbitMQSettings__Retries=3
   ports:
     - "5001:80"


volumes:
  microshop-catalog-data:
   external: false