version: '3.4'

services:
  rabbitmq:
   image: rabbitmq:3.9-management

  catalog-data:
   image: mcr.microsoft.com/mssql/server:latest

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    depends_on:
    - catalog-data
    - rabbitmq

  basket-data:
   image: redis:latest

  basket-api:
   image: ${DOCKER_REGISTRY-}basket-api
   depends_on:
    - basket-data
    - rabbitmq

  ordering-api:
   image: ${DOCKER_REGISTRY-}ordering-api
   depends_on:
    - rabbitmq
