version: '3.4'

services:
  rabbitmq:
   image: rabbitmq:3.9-management

  catalog-data:
   image: mcr.microsoft.com/mssql/server:latest

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    depends_on:
    - catalog-data
    - rabbitmq
