version: '3.4'

services:
  rabbitmq:
   image: rabbitmq:3.9-management

  identity-data:
   image: mcr.microsoft.com/mssql/server:latest

  identity-api:
   image: ${DOCKER_REGISTRY-}identity-api
   depends_on:
    - identity-data

  catalog-data:
    image: mongo:latest

  catalog-integration-data:
   image: mcr.microsoft.com/mssql/server:latest

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    depends_on:
    - catalog-data
    - rabbitmq

  basket-data:
   image: redis:latest

  basket-api:
   image: ${DOCKER_REGISTRY-}basket-api
   depends_on:
    - basket-data
    - rabbitmq

  ordering-data:
   image: mcr.microsoft.com/mssql/server:latest

  ordering-api:
   image: ${DOCKER_REGISTRY-}ordering-api
   depends_on:
    - ordering-data
    - rabbitmq

  ordering-signalr:
   image: ${DOCKER_REGISTRY-}ordering-signalr
   depends_on:
    - rabbitmq

  payment-api:
   image: ${DOCKER_REGISTRY-}payment-api

  web-api:
   image: ${DOCKER_REGISTRY-}web-api
   depends_on:
    - catalog-api
    - basket-api
    - ordering-api
    - payment-api
    - identity-api

  web-monitoring:
   image: ${DOCKER_REGISTRY-}web-monitoring
   depends_on:
    - web-api